baseURL = "https://sprblm.github.io/devs-guide-to/"
languageCode = 'en-us'
title = 'A devs guide to...'
theme = "terminal"
publishDir = "docs"

[params]
contentTypeName = "posts"
themeColor = "green"
showMenuItems = 8
fullWidthTheme = false
centerTheme = true

favicon = "favicon.ico"

[languages]
[languages.en]
title = "A devs guide to..."
subtitle = "A devs guide to..."
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "A devs guide to..."
logoHomeLink = "/devs-guide-to/"
[languages.en.menu]
[[languages.en.menu.main]]
identifier = "a-dev-guide-to-usertesting"
name = "User testing"
url = "/user-testing"
weight = 1
[[languages.en.menu.main]]
identifier = "synthesis-for-open-source"
name = "Synthesis for open-source"
url = "/synthesis-for-open-source"
weight = 2
[[languages.en.menu.main]]
identifier = "synthesis-for-open-source"
name = "Synthesis for open-source"
url = "/synthesis-for-open-source"
weight = 3
[[languages.en.menu.main]]
identifier = "Prioritization"
name = "Prioritization"
url = "/prioritization"
weight = 4
[[languages.en.menu.main]]
identifier = "updates"
name = "Updates"
url = "/updates"
weight = 5
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 6
